name: publish to maven

on:
  push:
    tags: [v*.*.*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p ~/.gnupg
      name: gpg dir
    - run: mkdir -p ~/.sbt/1.0
      name: sbt dir
    - name: set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      
    - shell: bash
      env:
        SONASECRET: ${{ secrets.SONASECRET }}
      run: |
        echo "$SONASECRET" > ~/.sbt/1.0/sonatype.sbt 

    - shell: bash
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
      run: |
        echo -n "$GPG_KEY" | base64 --decode | gpg --import

    - shell: bash
      env:
        SONA_CRE: ${{ secrets.SONA_CRE }}
      run: |
        echo "$SONA_CRE" > ~/.sbt/sonatype_credential 
        
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: publish to maven
      run: sbt test publishSigned sonatypeBundleRelease
